swagger: '2.0'
info:
  version: 1.0.0
  title: Sample application
  license:
    name: APL2
basePath: /api
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /users/uppercase:
    get:
      tags:
        - UsersUpperCase
      description: Get uppercased users
      responses:
        '200':
          description: Return uppercased users
  /users:
    get:
      tags:
      - Users
      description: Get hardcoded users
      responses:
        '200':
          description: Returns the users
    post:
      tags:
      - Users
      description: Echo back the user specified in the request
      parameters:
      - name: user
        description: The user
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: Echo the request inputs
  /pets:
    get:
      tags:
        - Pets
      description: Get harcoded pets
      responses:
        '200':
          description: Return the pets
    post:
      tags:
        - Pets
      description: Echo back the pet specified in the request
      parameters:
      - name: pet
        description: The pet
        in: body
        required: true
        schema:
          $ref: '#/definitions/Pet'
      responses:
        '200':
          description: Echo the request inputs
definitions:
  User:
    required:
    - firstname
    - lastname
    properties:
      firstname:
        type: string
      lastname:
        type: string
    example:
      firstname: carmine
      lastname: d
  Pet:
    required:
      - name
      - species
    properties:
      name:
        type: string
      species:
        type: string
    example:
      name: luna
      species: cat
